project:
  type: website
  output-dir: docs

website:
  title: "Differentiation"
  page-navigation: false
  back-to-top-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    fig-width: 8
    fig-height: 6
    fig-dpi: 150

execute:
  warning: false
  message: false
